---
- hosts: all
  become: true
  tasks:

    - name: install apache and php (Red Hat)
      yum:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"


